---
title: "Summary and discussion"
output: html_notebook
---

Workflow for the analysis of genomics populations and environmental variables for _Quercus macdougallii_ under construction

# Analysis of environmental variables

For this analysis the libraries were used:
install.packages ("raster")
install.packages ("dismo")
install.packages ("rJava")
install.packages ("spocc")
install.packages ("rgbif")
install.packages ("rgeos")

The 19 current environmental variables were obtained from the [WorldClim portal](https://www.worldclim.org/)

First we need to clean the data wich is remove spatially repeated data in a radius of 1km2. This is in the script **2.1clean_data.R**
```{r}
source("../bin/2.1_clean_data.R", echo = T)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
